version: '3'

services:
  backend:
    build:
      context: ../
      dockerfile: docker/backend.Dockerfile
    container_name: smartyoga-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/smartyoga
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES_IN=30d
      - NODE_ENV=production
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    build:
      context: ../
      dockerfile: docker/frontend.Dockerfile
    container_name: smartyoga-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  mongodb:
    image: mongo:4.4
    container_name: smartyoga-mongo
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongodb-data: